enable lint in enforcing mode
fail the build in case of syntax or include errors when using
the OpenBSD lint utility

Aegis-Change: anoubis.10.700.C109 Delta 42
Bug: 377
TE BLE

diff --git a/lint/lint.in b/lint/lint.in
--- a/lint/lint.in
+++ b/lint/lint.in
@@ -53,6 +53,10 @@ fatal () {
 	exit 1
 }
 
+error () {
+	echo "$*" >&2
+}
+
 set +e
 PARAMS=`getopt dho: "$@"`
 if test $? -ne 0; then usage; exit 1; fi;
@@ -89,7 +93,19 @@ set -e
 
 debug "lint exit code: $?"
 
-# XXX ignore any error codes for now. lint is behaving strange here...
+if egrep "\.h: No such file or directory" $STDOUT; then
+	error "Aborted due to missing includes"
+	error $STDERR
+	error $STDOUT
+	exit 1
+fi
+
+if egrep "syntax error" $STDOUT; then
+	error "lint failed to parse the source file"
+	error $STDERR
+	error $STDOUT
+	exit 1
+fi
 
 cat $STDERR > ${OUTPUTFILE}
 cat $STDOUT >> ${OUTPUTFILE}
