introduce missing types to splint properly
update some source files files to include a splint-includes.h header,
which is necessary for scanning with splint

Aegis-Change: anoubis.10.700.C110 Delta 47
Bug: 377
TE BLE

diff --git a/lint/splint.in b/lint/splint.in
--- a/lint/splint.in
+++ b/lint/splint.in
@@ -98,6 +98,13 @@ if egrep 'Parse Error' $STDERR || egrep 'Cannot find include file' $STDOUT; then
 	exit 1
 fi
 
+if egrep '^*** Cannot continue' $STDERR; then
+	echo "Error while running splint:" >&2
+	cat $STDERR >&2
+	cat $STDOUT >&2
+	exit 1
+fi
+
 if egrep '^Finished checking --- no warnings$' $STDERR; then
 	echo "" >$OUTPUTFILE
 	exit 0
